apiVersion: batch/v1
kind: Job
metadata:
  name: process-item-$ITEM
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: jobexample
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: c
        image: busybox:latest
        imagePullPolicy: Never
        command: ["/bin/sh","-c","echo Processing $ITEM && sleep 5"]
      restartPolicy: Never 
      
